# Provide sensible default application configuration settings.

exchange-rate:
  url: https://api.exchangerate.host/
  default-currency: EUR

spring:
  datasource:
    url: jdbc:h2:mem:transactioncommission
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-ui
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
